version: 2.1

orbs:
  node: circleci/node@5

jobs:
  build-vue:
    executor: node/default
    steps:
      - checkout

      - node/install-packages:
          pkg-manager: npm # or change to yarn if you're using yarn

      - run:
          name: Build Vue app
          command: npm run build

      - run:
          name: Create the ~/artifacts directory if it doesn't exist
          command: mkdir -p ~/artifacts

      - run:
          name: Copy build artifacts
          command: cp -R dist ~/artifacts 2>/dev/null || true

      - store_artifacts:
          path: ~/artifacts
          destination: vue-build

  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: deploy
          command: '# e.g. ./deploy.sh'

  trivy-scan:
    docker:
      - image: aquasec/trivy:latest
    steps:
      - checkout
      - run:
          name: Scan Dockerfile with Trivy
          command: trivy config --exit-code 0 --format table --output trivy-results.txt Dockerfile
      - store_artifacts:
          path: trivy-results.txt
          destination: trivy-scan-results

  runner-test:
    machine: true
    resource_class: my-runner/testing
    steps:
      - run: echo "Hi I'm on Runners!"

workflows:
  build:
    jobs:
      - build-vue
      - trivy-scan:
          requires:
            - build-vue
  testing:
    jobs:
      - runner-test
